export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ITEM_LISTS_SUCCESS = "LOAD_COURSES_SUCCESS";
export const ADD_ITEMS_LIST_SUCCESS = "ADD_ITEMS_LIST_SUCCESS";
export const REMOVE_ITEMS_LIST_SUCCESS = "REMOVE_ITEMS_LIST_SUCCESS";

export const LOAD_ITEMS_FOR_LIST_SUCCESS="LOAD_ITEMS_FOR_LIST_SUCCESS";
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_USERS_BY_NAME_SUCCESS = 'GET_USERS_BY_NAME_SUCCESS';
export const GET_USERS_BY_ID_SUCCESS = 'GET_USERS_BY_ID_SUCCESS';

export const SHARE_LIST_WITH_USER_SUCCESS = 'SHARE_LIST_WITH_USER_SUCCESS';

