export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const ADD_ITEMS_LIST = "ADD_ITEMS_LIST";
export const REMOVE_ITEMS_LIST = "REMOVE_ITEMS_LIST";

export const LOAD_ITEM_LISTS_SUCCESS = "LOAD_COURSES_SUCCESS";
